### ISSUE TITLE
undefined reference to `balde_make_response'

### ISSUE THREAD

**Issue by imjacobclark** [balde/balde#11]
With this Dockerfile (forked from the original to include the compilation step), I get a series of errors upon the compilation step.

Following the documentation, this is what is expected in order to compile a sample application.

It appears that possible balde isn't being brought in correctly as a library, is there a step missed in the container setup?

Output:

``` shell
/tmp/ccVwsoS7.o: In function `hello':
main.c:(.text+0x16): undefined reference to `balde_make_response'
/tmp/ccVwsoS7.o: In function `main':
main.c:(.text+0x2c): undefined reference to `balde_app_init'
main.c:(.text+0x51): undefined reference to `balde_app_add_url_rule'
main.c:(.text+0x5d): undefined reference to `balde_app_run'
main.c:(.text+0x69): undefined reference to `balde_app_free'
collect2: error: ld returned 1 exit status
```

Dockerfile:

``` Dockerfile
FROM ubuntu:14.04
MAINTAINER Rafael G. Martins <rafael@rafaelmartins.eng.br>

ENV version=0.1.2

RUN apt-get update && apt-get install -y \
    pkg-config gettext zlib1g-dev libffi-dev \
    autoconf automake build-essential libtool libxml2-utils \
    libfcgi-dev shared-mime-info libglib2.0-dev wget peg ca-certificates \
    --no-install-recommends && apt-get clean

RUN wget https://github.com/balde/balde/releases/download/v${version}/balde-${version}.tar.xz && tar xvf balde-${version}.tar.xz

RUN cd balde-${version} && \
    ./autogen.sh && \
    ./configure --prefix=/usr && \
    make && \
    make install

COPY . /usr/src/workspace
WORKDIR /usr/src/workspace
RUN gcc -o app $(pkg-config --libs --cflags balde) main.c
CMD ["./app"]
```

Source:

``` c
#include <balde.h>

balde_response_t*
hello(balde_app_t *app, balde_request_t *request)
{
    return balde_make_response("Hello World! I'm the balde! :D");
}

int
main(int argc, char **argv)
{
    balde_app_t *app = balde_app_init();
    balde_app_add_url_rule(app, "hello", "/", BALDE_HTTP_GET,
        hello);
    balde_app_run(app);
    balde_app_free(app);
    return 0;
}
```

**Comment by rafaelmartins** [comment]
this looks like a linker problem. can you post the docker run log?

**Comment by backjoob** [comment]
I'm also getting this error when trying to build a hello world application and link it against the installed library. I've built and installed master from github. Output:

$ gcc \
> -v \
> -o hello $(pkg-config --libs --cflags balde) hello.c
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.9' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9) 
COLLECT_GCC_OPTIONS='-v' '-o' 'hello' '-pthread' '-I' '/usr/local/include' '-I' '/usr/local/include/glib-2.0' '-I' '/usr/local/lib/glib-2.0/include' '-L/usr/local/lib' '-mtune=generic' '-march=x86-64'
 /usr/lib/gcc/x86_64-linux-gnu/5/cc1 -quiet -v -I /usr/local/include -I /usr/local/include/glib-2.0 -I /usr/local/lib/glib-2.0/include -imultiarch x86_64-linux-gnu -D_REENTRANT hello.c -quiet -dumpbase hello.c -mtune=generic -march=x86-64 -auxbase hello -version -fstack-protector-strong -Wformat -Wformat-security -o /tmp/ccqKAHAo.s
GNU C11 (Ubuntu 5.4.0-6ubuntu1~16.04.9) version 5.4.0 20160609 (x86_64-linux-gnu)
	compiled by GNU C version 5.4.0 20160609, GMP version 6.1.0, MPFR version 3.1.4, MPC version 1.0.3
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
ignoring nonexistent directory "/usr/local/include/x86_64-linux-gnu"
ignoring nonexistent directory "/usr/lib/gcc/x86_64-linux-gnu/5/../../../../x86_64-linux-gnu/include"
ignoring duplicate directory "/usr/local/include"
  as it is a non-system directory that duplicates a system directory
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include/glib-2.0
 /usr/local/lib/glib-2.0/include
 /usr/lib/gcc/x86_64-linux-gnu/5/include
 /usr/local/include
 /usr/lib/gcc/x86_64-linux-gnu/5/include-fixed
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
GNU C11 (Ubuntu 5.4.0-6ubuntu1~16.04.9) version 5.4.0 20160609 (x86_64-linux-gnu)
	compiled by GNU C version 5.4.0 20160609, GMP version 6.1.0, MPFR version 3.1.4, MPC version 1.0.3
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
Compiler executable checksum: d079eab342c322d6be59e8628e10ae67
COLLECT_GCC_OPTIONS='-v' '-o' 'hello' '-pthread' '-I' '/usr/local/include' '-I' '/usr/local/include/glib-2.0' '-I' '/usr/local/lib/glib-2.0/include' '-L/usr/local/lib' '-mtune=generic' '-march=x86-64'
 as -v -I /usr/local/include -I /usr/local/include/glib-2.0 -I /usr/local/lib/glib-2.0/include --64 -o /tmp/ccwugf7b.o /tmp/ccqKAHAo.s
GNU assembler version 2.26.1 (x86_64-linux-gnu) using BFD version (GNU Binutils for Ubuntu) 2.26.1
COMPILER_PATH=/usr/lib/gcc/x86_64-linux-gnu/5/:/usr/lib/gcc/x86_64-linux-gnu/5/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/5/:/usr/lib/gcc/x86_64-linux-gnu/
LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/5/:/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/:/lib/x86_64-linux-gnu/:/lib/../lib/:/usr/lib/x86_64-linux-gnu/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/5/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-v' '-o' 'hello' '-pthread' '-I' '/usr/local/include' '-I' '/usr/local/include/glib-2.0' '-I' '/usr/local/lib/glib-2.0/include' '-L/usr/local/lib' '-mtune=generic' '-march=x86-64'
 /usr/lib/gcc/x86_64-linux-gnu/5/collect2 -plugin /usr/lib/gcc/x86_64-linux-gnu/5/liblto_plugin.so -plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper -plugin-opt=-fresolution=/tmp/cc2BaLFZ.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lpthread -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --sysroot=/ --build-id --eh-frame-hdr -m elf_x86_64 --hash-style=gnu --as-needed -dynamic-linker /lib64/ld-linux-x86-64.so.2 -z relro -o hello /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crt1.o /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/5/crtbegin.o -L/usr/local/lib -L/usr/lib/gcc/x86_64-linux-gnu/5 -L/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/5/../../.. -lbalde -lgio-2.0 -lgobject-2.0 -lglib-2.0 /tmp/ccwugf7b.o -lgcc --as-needed -lgcc_s --no-as-needed -lpthread -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/lib/gcc/x86_64-linux-gnu/5/crtend.o /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crtn.o
/tmp/ccwugf7b.o: In function `hello':
hello.c:(.text+0x16): undefined reference to `balde_make_response'
/tmp/ccwugf7b.o: In function `main':
hello.c:(.text+0x2c): undefined reference to `balde_app_init'
hello.c:(.text+0x51): undefined reference to `balde_app_add_url_rule'
hello.c:(.text+0x66): undefined reference to `balde_app_run'
hello.c:(.text+0x72): undefined reference to `balde_app_free'
collect2: error: ld returned 1 exit status

**Comment by rafaelmartins** [comment]
if you want to build some app yourself you need the library installed system-wide with `make install` or `sudo make install`, otherwise gcc won't find the libraries. It should be possible to do it without installing, but this is advanced usage. If you want to do it, google for `PKG_CONFIG_PATH`

if you did that already, send the output of `pkg-config --libs --cflags balde`

**Comment by backjoob** [comment]
I installed it system-wide with "sudo make install."

$ pkg-config --libs --cflags balde
-pthread -I/usr/local/include -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -L/usr/local/lib -lbalde -lgio-2.0 -lgobject-2.0 -lglib-2.0

**Comment by rafaelmartins** [comment]
hmm, it looks correct. I'll take a look

**Comment by backjoob** [comment]
Any update?
