### ISSUE TITLE
Can't complete installation - pkg

### ISSUE THREAD

**Issue by rayymlai** [balde/balde#13]
I am unable to complete installation on CentOS 7 due to some dependencies which are undocumented.  I install balde binaries with fastcgi dependencies. I install pkgconfig but your package does not explain how to complete the path setup. While I compile your example codes, it won't run. Please help.

Here're my installation steps

**1. download balde**
https://github.com/balde/balde/releases
or simply download the tar file https://github.com/balde/balde/releases/download/v0.1.2/balde-0.1.2.tar.gz

**2. install fastcgi**

```
sudo yum install gcc gcc-c++ autoconf automake
sudo yum install fcgi-devel spawn-fcgi
```

then cd to balde binary
`./configure`

**3. install pkg-config**
https://www.freedesktop.org/wiki/Software/pkg-config/

`sudo ./configure && sudo make && sudo make install`

`export PKG_CONFIG_PATH=/home/ray/dev/balde/pkg-config-0.29.1`

```
gcc -o hello $(pkg-config --libs --cflags balde) hello.c
Package balde was not found in the pkg-config search path.
Perhaps you should add the directory containing 'balde.pc'
to the PKG_CONFIG_PATH environment variable
No package 'balde' found
hello.c:16:19: fatal error: balde.h: No such file or directory
 #include <balde.h>
                   ^
compilation terminated.
```

**Comment by rafaelmartins** [comment]
`PKG_CONFIG_PATH` should point to the directory where you installed `balde.pc` (probably `/usr/local/lib/pkgconfig`, but may change depending on your system/distro)

please run this command to find where the file was installed:

    $ find / -name balde.pc -type f

Thanks
