### ISSUE TITLE
can't compile test

### ISSUE THREAD

**Issue by jamesalbert** [balde/balde#16]
On OS X El Capitan v10.11.4

Here is my code: test.c

```
#include <stdio.h>
#include <balde.h>

int main() {
    return 0;
}
```

outputs

```
$ gcc test.c -o test
In file included from test.c:2:
In file included from /usr/local/include/balde.h:12:
/usr/local/include/balde/app.h:12:10: fatal error: 'glib.h' file not found
#include <glib.h>
         ^
1 error generated.
```

I ran configure, make, sudo make install and everything went smoothly (except for `make check` which I created an issue for just before this one)

edit: I also wanted to say I for sure have glib ;) I also tried linking it with no luck

**Comment by rafaelmartins** [comment]
you must ask gcc to link to glib and balde, running something like:

    $ gcc test.c -o test $(pkg-config --cflags --libs balde)

**Comment by jamesalbert** [comment]
Awesome, that compiled it. thanks! But when I run ./test binary, it gives this:

```
objc[62322]: Class GNotificationCenterDelegate is implemented in both /opt/local/lib/libgio-2.0.0.dylib and /usr/local/opt/glib/lib/libgio-2.0.0.dylib. One of the two will be used. Which one is undefined
```

Sorry, I'm not a c person. Still trying to learn.

**Comment by rafaelmartins** [comment]
From the error message, it seems that you have glib installed twice in your system. I'd like to be more helpful but I don't know a lot about mac os x :(

**Comment by jamesalbert** [comment]
Thank you I know exactly why that's happening (damn myself and my careless use of macport)!
