### ISSUE TITLE
Desenvolvimento no Windows

### ISSUE THREAD

**Issue by rafamds** [balde/balde#20]
Olá,
sou programador de PHP, mas vi esta microframework e achei interessante. Achei que podia ser útil no caso de querer aprender a desenvolver em C, seja aplicações web ou outras coisas, porque sempre ouvi falar muito bem de C. 

Gostava de saber se é possível, e se sim como, posso utilizar esta microframework em ambiente Windows :)

Obrigado,
Abraços.

**Comment by canassa** [comment]
Olá Rafael,

Respondendo a sua pergunta: O balde funciona sim em Windows, você vai precisar garantir que a .dll da glib esteja instalada mas fora isso deve funcionar. Um outro caminho (provavelmente muito mais simples) seria você usar um Vagrant ou um Docker para rodar um ambiente de desenvolvimento Linux dentro do seu Windows. Infelizmente eu não acesso a nenhuma máquina Windows então eu não posso te dar um passo-a-passo mais detalhado.

Mas saindo um pouco do que você perguntou, se o seu objetivo é aprender C eu particularmente não recomendaria começar com um microframework como o balde. Mesmo um microframework pequeno como o balde já é um projeto relativamente complexo e utiliza um lib bem grande como dependencia (glib). Eu particularmente começaria seguindo pelo livro do K&R e depois iria me familiarizando escrevendo algumas ferramentas simple que usam só a linha de comando mesmo, é importante que você se familiarize não só com a linguagem mas com toda a toolchain ao redor dela (gdb, compiladores, Makefiles, etc)


Abraços!

**Comment by ptraceur** [comment]
Muito obrigado pela resposta, vou seguir o conselho.

Abraços 👍
